language: java
jdk: oraclejdk7
env:
  global:
    - secure: UXObAmTHk0/J5n5xohMKwOujxHrdLuraq7/5Jesxlluit2pGT8EiEJaoAZokTNJuqEylIbRWWT3nry9Y9z7ISRVEbcRgioalFuK4rfXyBayJ1Fnt6Y/2VWjDMmIvEf2F/sT9kad1y9SfTyFouAsr2PdqBCRgN+hA5X+Al9W0ic4=

before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
  - tar xzf android-sdk_r22.3-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

  # Install required components.
  # For a full list, run `android list sdk -a --extended`
  # Note that sysimg-18 downloads the ARM, x86 and MIPS images (we should optimize this).
  - echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
  - echo yes | android update sdk --filter build-tools-19.0.1 --no-ui --force > /dev/null
  - echo yes | android update sdk --filter android-19 --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-google-google_play_services --no-ui --force > /dev/null

  # We have to use the '--all' parameter because the SDK is weird an does not think we should be able to install this.
  - echo yes | android update sdk --filter extra-google-m2repository --all --no-ui --force > /dev/null

  # Add Google Maps API key to project
  - echo $MAPKEY >> StudyWithFriends/src/main/res/values/map_key.xml

script:
  - ./gradlew test --info
